### ISSUE TITLE
the home page keeps reloading

### ISSUE THREAD

**Issue by maxadamo** [vagharsh/consul-tree#31]
once I authenticate, the page enters an endless loop, and keeps reloading forever. 

I am running Consul v1.15.3, and I use an authentication token. 

On a different note, I also tried to build the image, but it's too old and the debian image fails to download the packages. The good news is that the applications seems to work with php8.3.0

**Comment by maxadamo** [comment]
the loop ends if I remove `lib/jquery-3.2.1.min.js`

**Comment by vagharsh** [comment]
hi @maxadamo sorry for the late reply, could you open a pull request with the fix ? 
it has been very long time since i have updated anything in my code since there were no major changes needed .. and i am using the pre-build docker images for this..

**Comment by vagharsh** [comment]
issue has been fixed with the 7.5.3 release including php image updates. and jquery version updates
